jenkins_plugins:
- "role-strategy:575.v4d286a_03e6d7"
- "credentials:1214.v1de940103927"
jenkins_users:
- name: 'blue'
  password: 'redteamiscoming'
- name: 'rsanchez'
  password: 'salespower'
- name: 'ebelford'
  password: 'ebelford'
- name: 'mwallace'
  password: '123456789'
- name: 'lmurphy'
  password: 'qwerty'
- name: 'dlee'
  password: 'rg885q0ga3vmvm'
- name: 'pkim'
  password: '1qazxsW@1'
- name: 'rgill'
  password: 'A3daD44InF!u'
- name: 'ranthony'
  password: '0V14nHhCh'
- name: 'bob'
  password: '0V14ngrgaHhCh'
ssh_users:
- name: 'zcool'
  password: 'A3daD44InF!u'
  group: 'sudo'
- name: 'lnikon'
  password: '0V14n&@Hh$Ch'
  group: 'sudo'
- name: 'bob'
  password: '0V14n&@grgaHh$Ch'
  group: ''
- name: 'lmurphy'
  password: 'qwerty'
  group: ''
- name: 'mwallace'
  password: '123456789'
  group: 'sudo'
- name: 'lmurphy'
  password: 'qwerty'
  group: 'sudo'
