---
- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Add nginx jenkins config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644

- name: "Restart nginx service"
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
